spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ai_docs}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  ai:
    openai:
      base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
      api-key: api_key_here
      chat:
        enabled: true
        options:
          model: ${OPENAI_CHAT_MODEL:gpt-4}
          temperature: ${OPENAI_TEMPERATURE:0.5}
          max-tokens: ${OPENAI_MAX_TOKENS:8000}
